fos_rest:
    view:
        view_response_listener:  true
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
        codes:
            \InvalidArgumentException: 400
            Doctrine\ORM\EntityNotFoundException: 404
            \LogicException: 400
            \DomainException: 400
        messages:
            \InvalidArgumentException: true
            Doctrine\ORM\EntityNotFoundException: true
            \LogicException: true
            \DomainException: true
